apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.db.secret.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.secret.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_DB: {{ .Values.db.secret.POSTGRES_DB | b64enc | quote }}
