// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: api/marks.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message definition for marks.
type Marks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentId string `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Sub_1     int32  `protobuf:"varint,2,opt,name=sub_1,json=sub1,proto3" json:"sub_1,omitempty"`
	Sub_2     int32  `protobuf:"varint,3,opt,name=sub_2,json=sub2,proto3" json:"sub_2,omitempty"`
	Sub_3     int32  `protobuf:"varint,4,opt,name=sub_3,json=sub3,proto3" json:"sub_3,omitempty"` // Add other fields as needed
}

func (x *Marks) Reset() {
	*x = Marks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_marks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Marks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Marks) ProtoMessage() {}

func (x *Marks) ProtoReflect() protoreflect.Message {
	mi := &file_api_marks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Marks.ProtoReflect.Descriptor instead.
func (*Marks) Descriptor() ([]byte, []int) {
	return file_api_marks_proto_rawDescGZIP(), []int{0}
}

func (x *Marks) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Marks) GetSub_1() int32 {
	if x != nil {
		return x.Sub_1
	}
	return 0
}

func (x *Marks) GetSub_2() int32 {
	if x != nil {
		return x.Sub_2
	}
	return 0
}

func (x *Marks) GetSub_3() int32 {
	if x != nil {
		return x.Sub_3
	}
	return 0
}

// Message definition for a request to create marks.
type CreateMarksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Marks *Marks `protobuf:"bytes,1,opt,name=marks,proto3" json:"marks,omitempty"`
}

func (x *CreateMarksRequest) Reset() {
	*x = CreateMarksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_marks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarksRequest) ProtoMessage() {}

func (x *CreateMarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarksRequest.ProtoReflect.Descriptor instead.
func (*CreateMarksRequest) Descriptor() ([]byte, []int) {
	return file_api_marks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMarksRequest) GetMarks() *Marks {
	if x != nil {
		return x.Marks
	}
	return nil
}

// Message definition for a response to create marks.
type CreateMarksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateMarksResponse) Reset() {
	*x = CreateMarksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_marks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarksResponse) ProtoMessage() {}

func (x *CreateMarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarksResponse.ProtoReflect.Descriptor instead.
func (*CreateMarksResponse) Descriptor() ([]byte, []int) {
	return file_api_marks_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMarksResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Message definition for a request to retrieve marks by student ID.
type GetMarksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentId string `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
}

func (x *GetMarksRequest) Reset() {
	*x = GetMarksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_marks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarksRequest) ProtoMessage() {}

func (x *GetMarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarksRequest.ProtoReflect.Descriptor instead.
func (*GetMarksRequest) Descriptor() ([]byte, []int) {
	return file_api_marks_proto_rawDescGZIP(), []int{3}
}

func (x *GetMarksRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

// Message definition for a response to retrieve marks by student ID.
type GetMarksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Marks *Marks `protobuf:"bytes,1,opt,name=marks,proto3" json:"marks,omitempty"`
}

func (x *GetMarksResponse) Reset() {
	*x = GetMarksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_marks_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarksResponse) ProtoMessage() {}

func (x *GetMarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marks_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarksResponse.ProtoReflect.Descriptor instead.
func (*GetMarksResponse) Descriptor() ([]byte, []int) {
	return file_api_marks_proto_rawDescGZIP(), []int{4}
}

func (x *GetMarksResponse) GetMarks() *Marks {
	if x != nil {
		return x.Marks
	}
	return nil
}

// Message definition for a request to update marks.
type UpdateMarksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentId string `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Marks     *Marks `protobuf:"bytes,2,opt,name=marks,proto3" json:"marks,omitempty"`
}

func (x *UpdateMarksRequest) Reset() {
	*x = UpdateMarksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_marks_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMarksRequest) ProtoMessage() {}

func (x *UpdateMarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marks_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMarksRequest.ProtoReflect.Descriptor instead.
func (*UpdateMarksRequest) Descriptor() ([]byte, []int) {
	return file_api_marks_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMarksRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *UpdateMarksRequest) GetMarks() *Marks {
	if x != nil {
		return x.Marks
	}
	return nil
}

// Message definition for a response to update marks.
type UpdateMarksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateMarksResponse) Reset() {
	*x = UpdateMarksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_marks_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMarksResponse) ProtoMessage() {}

func (x *UpdateMarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marks_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMarksResponse.ProtoReflect.Descriptor instead.
func (*UpdateMarksResponse) Descriptor() ([]byte, []int) {
	return file_api_marks_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMarksResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Message definition for a request to delete marks by student ID.
type DeleteMarksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentId string `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
}

func (x *DeleteMarksRequest) Reset() {
	*x = DeleteMarksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_marks_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMarksRequest) ProtoMessage() {}

func (x *DeleteMarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_marks_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMarksRequest.ProtoReflect.Descriptor instead.
func (*DeleteMarksRequest) Descriptor() ([]byte, []int) {
	return file_api_marks_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMarksRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

// Message definition for a response to delete marks by student ID.
type DeleteMarksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteMarksResponse) Reset() {
	*x = DeleteMarksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_marks_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMarksResponse) ProtoMessage() {}

func (x *DeleteMarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_marks_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMarksResponse.ProtoReflect.Descriptor instead.
func (*DeleteMarksResponse) Descriptor() ([]byte, []int) {
	return file_api_marks_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMarksResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_marks_proto protoreflect.FileDescriptor

var file_api_marks_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x65, 0x0a, 0x05, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x13,
	0x0a, 0x05, 0x73, 0x75, 0x62, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73,
	0x75, 0x62, 0x31, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x5f, 0x32, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x75, 0x62, 0x32, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x75, 0x62, 0x5f,
	0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x75, 0x62, 0x33, 0x22, 0x36, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x05,
	0x6d, 0x61, 0x72, 0x6b, 0x73, 0x22, 0x2d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x30, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x6d, 0x61,
	0x72, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x05, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x22, 0x55, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x05, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x05, 0x6d, 0x61,
	0x72, 0x6b, 0x73, 0x22, 0x2f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x33, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61,
	0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x99, 0x02, 0x0a, 0x0c, 0x4d,
	0x61, 0x72, 0x6b, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x50, 0x43, 0x12, 0x17, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x50, 0x43, 0x12,
	0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x50, 0x43, 0x12, 0x17,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x43, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73,
	0x52, 0x50, 0x43, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_marks_proto_rawDescOnce sync.Once
	file_api_marks_proto_rawDescData = file_api_marks_proto_rawDesc
)

func file_api_marks_proto_rawDescGZIP() []byte {
	file_api_marks_proto_rawDescOnce.Do(func() {
		file_api_marks_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_marks_proto_rawDescData)
	})
	return file_api_marks_proto_rawDescData
}

var file_api_marks_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_marks_proto_goTypes = []interface{}{
	(*Marks)(nil),               // 0: api.Marks
	(*CreateMarksRequest)(nil),  // 1: api.CreateMarksRequest
	(*CreateMarksResponse)(nil), // 2: api.CreateMarksResponse
	(*GetMarksRequest)(nil),     // 3: api.GetMarksRequest
	(*GetMarksResponse)(nil),    // 4: api.GetMarksResponse
	(*UpdateMarksRequest)(nil),  // 5: api.UpdateMarksRequest
	(*UpdateMarksResponse)(nil), // 6: api.UpdateMarksResponse
	(*DeleteMarksRequest)(nil),  // 7: api.DeleteMarksRequest
	(*DeleteMarksResponse)(nil), // 8: api.DeleteMarksResponse
}
var file_api_marks_proto_depIdxs = []int32{
	0, // 0: api.CreateMarksRequest.marks:type_name -> api.Marks
	0, // 1: api.GetMarksResponse.marks:type_name -> api.Marks
	0, // 2: api.UpdateMarksRequest.marks:type_name -> api.Marks
	1, // 3: api.MarksService.CreateMarksRPC:input_type -> api.CreateMarksRequest
	3, // 4: api.MarksService.GetMarksRPC:input_type -> api.GetMarksRequest
	5, // 5: api.MarksService.UpdateMarksRPC:input_type -> api.UpdateMarksRequest
	7, // 6: api.MarksService.DeleteMarksRPC:input_type -> api.DeleteMarksRequest
	2, // 7: api.MarksService.CreateMarksRPC:output_type -> api.CreateMarksResponse
	4, // 8: api.MarksService.GetMarksRPC:output_type -> api.GetMarksResponse
	6, // 9: api.MarksService.UpdateMarksRPC:output_type -> api.UpdateMarksResponse
	8, // 10: api.MarksService.DeleteMarksRPC:output_type -> api.DeleteMarksResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_marks_proto_init() }
func file_api_marks_proto_init() {
	if File_api_marks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_marks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Marks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_marks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMarksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_marks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMarksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_marks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMarksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_marks_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMarksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_marks_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMarksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_marks_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMarksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_marks_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMarksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_marks_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMarksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_marks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_marks_proto_goTypes,
		DependencyIndexes: file_api_marks_proto_depIdxs,
		MessageInfos:      file_api_marks_proto_msgTypes,
	}.Build()
	File_api_marks_proto = out.File
	file_api_marks_proto_rawDesc = nil
	file_api_marks_proto_goTypes = nil
	file_api_marks_proto_depIdxs = nil
}
